### ISSUE TITLE
Multi-Party Escrow

### ISSUE THREAD

**Issue by ldub** [singnet/platform-contracts#30]
Expose a smart-contract interface for allocating AGI tokens towards use in calling AI Services on the SingularityNET Network that can be held in escrow on the blockhain until services are delivered or the tokens are deallocated. 

Support payment channels for off-chain transfers of AGI tokens between an AI Service and client for later on-chain settlement enabling real-time interaction without round-trips to the blockchain.

**Comment by astroseger** [comment]
done by https://github.com/singnet/platform-contracts/pull/39

**Comment by ldub** [comment]
I saw this was closed and want to note that the original design was to enable users to open a single channel with SNET and pay for many different services with it. @vforvalerio87 can corroborate that this was the original intention.

Because if you think about it, creating a UX where consumers have to open a new channel for every service is a pretty low bar.

Just some food for thought, wanted to mention this because I see that I didn't say any of this in the original issue.

**Comment by astroseger** [comment]
Hi!
What exactly do you mean by design in which the client open the single channel for many different servers? 
I see two possible interpretation of your original design. I'm particular interesting in the number of on-chain transactions. 
1. Do you mean the following scenario:
- The client put some AGI tokens in MPE
- The client can start to work with different services, but in order to start working we need to open an "atomic" channel between the client and the server.  You can see it as reservation of part of client's tokens by the server. In any case there is one on-chain transaction (from the server or from the client).
If it is what you meant, then we already have it. Please see discussion here: https://github.com/singnet/platform-contracts/issues/47
2. Or do you mean the following scenario:
 - The client put money in MPE (on-chain transaction)
 - The client starts to use different servers without any on-chain transactions.

If it is what you meant, then please describe your design, because I don't see how it is possible. I'm especially interesting in off-chain synchronization between servers in order to prevent overspending attack from the client.

**Comment by pennachin** [comment]
I think perhaps @ldub meant a single channel between a user and SingularityNET, with SNET then funnelling the funds to the service providers. We discussed something like that.

**Comment by astroseger** [comment]
My point was that we already have it, because we can consider out MPE as this "single channel" and then we call MPE.openChannel we kind of reserve tokens for the given service provider. 
And I tried to demonstrated that it is the only one secure way to do it, because we cannot avoid "reservation" of funds for specific service.

**Comment by astroseger** [comment]
So it was my question to @ldub. If you have some ideas how we could avoid on-chain call to reserve client's tokens for specific service provider, then I'm very curious to hear it, because it seems obvious that it is impossible. It is obvious because without off-chain synchronization between servers and without reservation of funds for specific service provider we cannot prevent overspending attack from the client.  I assumed that it was obvious for everybody, so I closed this issue.
 Because if in your architecture you have on-chain call to reserve funds, then we already have it (I call this reservation  as "openChannel", but if you want you can consider it as reservation of funds).
