### ISSUE TITLE
Remove build/contracts files from repository

### ISSUE THREAD

**Issue by vsbogd** [singnet/platform-contracts#52]
At the moment contract compilation results are kept in github.com repository under build/contracts folder and reason is unclear. PR https://github.com/singnet/platform-contracts/pull/34 contains some discussion around this question.

It is worth to change platform-contracts packaging procedure to not require keeping results of compilation in repository.

**Comment by astroseger** [comment]
I strongly support removing ABI files from githut. I think that putting ABI files to github was an error, because if we will update them at each commit then size of the repo will grow very fast. It is not a right way of using git. There is, certainly, should be an other way to solve the problem, without misusing git.

**Comment by astroseger** [comment]
was done by #64
