### ISSUE TITLE
Add a foundation user on the registry

### ISSUE THREAD

**Issue by raamb** [singnet/platform-contracts#88]
We should consider adding a foundation user to the registry contract who can delete services across any organizations. This is primarily a safety measure in case the registry gets spammed. One potential scenario is that somebody creates a very large number of services on the contract thereby making valid service registration very expensive.

@astroseger

**Comment by astroseger** [comment]
Price of service registration do not depend on total number of registered services (even inside one organization), so it shouldn't be a problem. Moreover it could be very bad from PR point of view....

**Comment by pennachin** [comment]
I think the potential for bad PR from obviously malicious contents in the registry is worse.

**Comment by astroseger** [comment]
@pennachin 
I. About spamming.
In short: No! Spamming is not a problem.....
- Gas price do not depends on total number of services (especially on total number of services in another organization). This include gas price for adding and removing tags. We've discussed it in HK: gas price for adding data to mapping do not depends significantly on size of mapping. So gas price is not a problem.
- Of course ```listOrganizations``` will return more organization and ```listServicesForTag``` will return more services with given tag. But we are going to filter the output of these function in any case, so it seems it is not a problem...

II. I'm not against the "foundation user" as a another layer against malicious content. However I will include @tiero and @vforvalerio87, because I think they might have different point of view.

From point of view of implementation --- it is very straightforward to implement it.

**Comment by ksridharbabuus** [comment]
@astroseger @raamb Shall we consider owner of the contract itself as a foundation member. Or do we have to maintain list of foundation members which can manage (especially Delete of Org/Service/Type).

I prefer to have Owner as a foundation member and he can Only delete not modify.

**Comment by astroseger** [comment]
@pennachin 
1. No! If we have "curated services" subsystem then possible spamming is not a problem even in the sense of "sheer volume of malicious/random contents added to the contract". I'm not against 'foundation user' as an additional layer against malicious content, but for sake of  truth I want to stress out that the argument  about "spamming" is wrong.
 We will probably have "curated services" subsystem in any case (see 2.). It means that end-user will call only ```getOrganizationById``` and ```getServiceRegistrationById``` (which are not affected by "spam" in any sense).  
2. It would be nice to replace "curated services" subsystem with "foundation user" but we cannot do it because we cannot remove organization/service immediately, so "malicious" organization/service will be presented in Registry for some time. If we do not want to show "malicious" service at all, we should have system of "curated services" ( or show services only after 1-2 days after registration to give us time to remove bad services). 


Implementation details:
It would be great that "foundation user" has rights to only call ```deleteOrganization```, but with on-chain tags it is not enough. One can easily prevent deleting service by adding ~30 tags. In order to remove such a service we need access to ```removeTagsFromServiceRegistration``` 

"foundation user" should have the right to call the following functions:
- ```removeTagsFromServiceRegistration```
- ```deleteServiceRegistration```
- ```deleteOrganization```

**Comment by astroseger** [comment]
The question is following: are we going to implement "foundation user" taking into account:
1. The "spam" argument is wrong (if we have "curated services" system ), so the only one function of "foundation user" is an additional layer of protection against malicious services. 
2. "foundation user" should have access to removing tags from any services and remove services from any organizations.

**Comment by pennachin** [comment]
We shouldn't assume everyone will use our curated services marketplace, though, otherwise there would be no reason to have non-curated entries in the registry at all. So spamming won't affect our marketplace, but will affect those who don't want to depend on our centralized add-ons to the registry...

**Comment by astroseger** [comment]
@pennachin  
Yes, It is true, for brave souls who don't follow our curated services recommendation the spamming will be a problem. 
In any case I'm not against "foundation user" (In the end, in my country we are rarely opposed to a bit of authoritarianism :) , but I surprise that our friends from more liberal places keep silence...)

@ksridharbabuus I would rather have the same system of owner/members as for an organization. It would allow us to have several censors...

**Comment by ksridharbabuus** [comment]
@astroseger I am thinking of adding one field called "foundationOwner" who has control over delete operations as you have mentioned.
We will set this field in the constructor as msg.sender (who created/deployed the contract).

Since it is only a fallback operation thinking of not have additional members or method to update this field. Hope it is aligned with your thoughts as well.

**Comment by ferrouswheel** [comment]
In essence the foundation user seems to be an argument for a back door for us to maintain control of the registry, and leans against the idea of decentralisation.

If this is implemented, we should come up with clear guidelines for the use of the power this user has. Not only so that this process is defined, but so the community doesn't think we're going to exert unnecessary control.

Anyone can still launch their own registry to get around this, so we should probably call it something different than "foundation user" and instead call it something like "registry curator".

**Comment by ksridharbabuus** [comment]
Will call it as a curator meaning custodian of the contract. Where the role of curator is to make sure that the right & valid Organization, Services, TypeRepos and Tags. He cannot update but only can delete where ever it is not aligned to regulations.

@ferrouswheel Yes we need to define the guideline to be part of readme document.

**Comment by astroseger** [comment]
@pennachin 
There is a possible issue with "foundation user" because by introducing foundation user we might actually introduce more legal responsibilities for us.  
- In the current version we cannot change Registry, so our responsibilities are similar to Ethereum foundation, because they also cannot control or modify smart contracts. 
- But if we have possibility to remove malicious content and we don't do it for some reason then we might, theoretically, have problems...

**Comment by pennachin** [comment]
This is a good point, @astroseger, will discuss with those in charge of regulatory aspects.

**Comment by raamb** [comment]
Closing this as we will not be add such a user.
